### ISSUE TITLE
Symmetric key encryption/decryption doesn't work

### ISSUE THREAD

**Issue by AGWA** [prologic/salt#1]
The following condition in `func encrypt` is always true since `pub` is always non-nil:

https://github.com/prologic/salt/blob/b4659f9a9d0595828f7d5e88b55204570220744a/main.go#L60

`pub` is always non-nil because `hex.DecodeString` in `func main` returns a non-nil slice:

https://github.com/prologic/salt/blob/b4659f9a9d0595828f7d5e88b55204570220744a/main.go#L133

Consequentially, the code for public key encryption is always executed, and the code for symmetric key encryption is unreachable.

There's a similar problem in `func decrypt`.

**Comment by prologic** [comment]
Can you put up a PR to fix this? THanks for the catch!
